### ISSUE TITLE
Error Output Error #

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/USX#13]
While processing https://github.com/unfoldingWord/ulb-en/blob/master/01-GEN-en-ULB.usfm I get:
(GEN)
Error: After Genesis 6:32 - Unknown Token: \v

There are only 22 verses in Genesis 6.

Note: I have identified the error to be at 6:1 however, it would be good to fix the error message to be more accurate.
Thanks

**Comment by neutrinog** [comment]
there have been similar issues to this where the error message tells you the problem is at one location but it is actually at another. see https://github.com/Door43/USFM-Tools/issues/5

**Comment by kbuildsyourdotcom** [comment]
There are 32 verses in Chapter 5. The chapter marker to move to 6 happens, but then verse marker 1 fails and therefore verse is not reset to 1. I will add code to reset the verse counter to 1 when a new chapter marker is found.

**Comment by kbuildsyourdotcom** [comment]
Fixed in https://github.com/neutrinog/USX/issues/16
